### ISSUE TITLE
@-Zeichen und \ funktioniert nicht 

### ISSUE THREAD

**Issue by Fs081** [MichaelDworkin/Fingerprint-Macro-Key-USB-HID#2]
Hallo! Ich bin begeistert von dem
Projekt. Alles hat super geklappt, leider gibt das Programm aber kein @-Zeichen aus (es wird immer ein q ausgegeben). Ebenso funktioniert der Backslash \ nicht, hier bricht die Ausgabe dann einfach ab. 
Gibt es dafür eine Lösung? 
VG und danke!!!

**Comment by MichaelDworkin** [comment]
Sie können ja per Befehl die tastenkombinationen senden

KEY_RIGHT_ALT     0x86 und q

"Ihre Text§p0x86 q §a " Presse RIGHT_ALT, dann 'q', dann alle loslassen.
Ich habe es jetzt nicht ausprobiert, sollte aber funktionieren

**Comment by Fs081** [comment]
Das klappt! 
Ich danke vielmals!
